// we need shape of user profile document
export interface UserProfile {
    $id: string; // this is generated by Appwrite
    user_id: string;
    email: string;
    role: "viewer" | "pending" | "scribe" | "admin";
    selected_courses: string[]; // array of course codes
    $createdAt: string;
    $updatedAt: string;
}

export interface Note{
    $id: string;
    title: string;
    course_code: string;
    professor: string;
    quarter: string;
    week: string;
    file_id: string;
    uploader_id: string;
    search_index: string;
    $createdAt: string;
    $updatedAt: string;
}